### ISSUE TITLE
Request: Custom format

### ISSUE THREAD

**Issue by tex** [asamuzaK/url2clipboard#100]
Hello,

my wanted workflow is as follows:

in Firefox have a button that copies page url to clipboard. Using CopyQ as clipboard manager with a custom automatic command that is executed everytime when a specific message (created by clicking on Firefox button) is added to clipboard. In my case it would download page using youtube-dl.

I could use your plugin with for example org mode link which I do not use often, but it would be nicer to have ability to
specify my own format/tag to not collide with anything that could go into clipboard normally.
Something like "youtube-dl: {}".format(url) ...

Thanks!

**Comment by asamuzaK** [comment]
What is CopyQ?

**Comment by tex** [comment]
https://hluk.github.io/CopyQ/

Clipboard manager with advanced features

**Comment by tex** [comment]
You can add custom action to it based on regexp/data in selection...

**Comment by asamuzaK** [comment]
I'm not going to implement a custom format that allows arbitrary input by the user.

**Comment by tex** [comment]
Fair enough. I found another extension that allows exactly what I need.
