### ISSUE TITLE
Review required permissions

### ISSUE THREAD

**Issue by Wolf-SO** [asamuzaK/url2clipboard#102]
To me, it's hard to understand how this add-on "needs" [*Access your data for all websites*](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_access-your-data-for-all-websites). Would you please clarify what makes this permission necessary, or (the better option in my opinion) reduce permissions to the minimum? Thanks in advance.

**Comment by asamuzaK** [comment]
I'm working on it.
See #103.
Once that PR is merged and next version released, then it will not require 'access your data for all websites' permission anymore.

**Comment by Wolf-SO** [comment]
@asamuzaK This is great news, thanks for taking a look!

**Comment by asamuzaK** [comment]
Now, it does not require 'access your data for all websites' permission.
![permisson](https://user-images.githubusercontent.com/6790339/129463084-e72e5dea-197e-4db6-b25a-d45553518abe.png)

**Comment by Wolf-SO** [comment]
I'm amazed, also that you didn't forget [to answer the review](https://addons.mozilla.org/de/firefox/addon/url2clipboard/reviews/1743396/) on the FF add-on page! Thanks a lot again.
