### ISSUE TITLE
Simple user cofig

### ISSUE THREAD

**Issue by agrabhi** [asamuzaK/url2clipboard#108]
I loved the extension as it simply can provide RTF alike copy formats. 

But there are too many options. I believe most popular use case is to copy url and title as RTF. Can it be provided with one click?

**Comment by asamuzaK** [comment]
>  Can it be provided with one click?

Not planned.
The format needed varies from person to person.

Open options page and check the format you need / uncheck the format you don't need.

**Comment by Wolf-SO** [comment]
Thanks, both of you, for the quick Q&A issue. 😊 I recently observed the menu being full of entries, but didn't find the time yet to check the options. BTW, I need more than one on a regular basis, so the solution you have chosen, @asamuzaK, is perfect.
