### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by itagagaki** [asamuzaK/url2clipboard#112]
I used to use it conveniently, but then I realized that it stopped working sometime ago. The contextual menu appears, but no matter which one I select, it doesn't copy to the clipboard.

add-on version: 7.1.0
Microsoft Edge  96.0
Google Chrome 96.0
Windows 10 Pro 21H1

Let me know if you need any more information.

**Comment by asamuzaK** [comment]
Confirmed

**Comment by asamuzaK** [comment]
v7.1.2 waiting for review.
After released, please check if the issue is fixed or not.

**Comment by itagagaki** [comment]
It is now working again. Thank you!
