### ISSUE TITLE
Context menu not shown

### ISSUE THREAD

**Issue by itagagaki** [asamuzaK/url2clipboard#114]
Recently stopped working
Browser version 99.0
Extention version 7.1.4

**Comment by alansalihi** [comment]
Same thing here. It seems that Chrome stopped showing this beautiful extension on the context menu. 
I tested it on two computers and two accounts. all show the same result (no context menu commands for this extension).

**Comment by andresgsepulveda** [comment]
Hi, just stumbled on this page. Also having the issue on Chrome Version 99.0.4844.51 (Official Build) (arm64), Extension Version 7.1.5.

**Comment by asamuzaK** [comment]
Confirmed

**Comment by asamuzaK** [comment]
Uploaded a new version v7.1.5.
It should be released after it's reviewed.
