### ISSUE TITLE
Suggest adding deep-linking features

### ISSUE THREAD

**Issue by zbh531** [asamuzaK/url2clipboard#117]
Hi! I really enjoy copying selected text as **Markdown** using this extension in order to make futher notes. However, copied URLs refer to orginal links instead of **deep links** (i.e., *"Copy link to highlight"* in the right-click menu in Chrome).

#### Example:
**Current result**: [An unspayed female is called a queen](https://en.wikipedia.org/wiki/Cat "Cat - Wikipedia")
*Source mode*: \[An unspayed female is called a queen\](https://en.wikipedia.org/wiki/Cat "Cat - Wikipedia") [^1]

**Suggested result**: [An unspayed female is called a queen](https://en.wikipedia.org/wiki/Cat#:~:text=An%20unspayed%20female%20is%20called%20a%20queen "Cat - Wikipedia") [^2]
*Source mode*: \[An unspayed female is called a queen\](https://en.wikipedia.org/wiki/Cat#:~:text=An%20unspayed%20female%20is%20called%20a%20queen "Cat - Wikipedia")

Thank you in advance for your attention to this matter.

[^1]: The "Add title attribute" option have been turned on in this example.
[^2]: This URL would be directed to highlighted text.

**Comment by asamuzaK** [comment]
Not yet standardized.
[Scroll to Text Fragment - Chrome Platform Status](https://chromestatus.com/feature/4733392803332096)
[WICG/scroll-to-text-fragment: Proposal to allow specifying a text snippet in a URL fragment](https://github.com/WICG/scroll-to-text-fragment)

I'm closing this for now.
Please reopen when it's spec'd.

**Comment by asamuzaK** [comment]
Although still in draft, all major browsers now support text fragments.
[Text fragments - URIs | MDN](https://developer.mozilla.org/en-US/docs/Web/URI/Fragment/Text_fragments)
[URL Fragment Text Directives](https://wicg.github.io/scroll-to-text-fragment/)

NOTE:
Since `rel=“noopener”` is required for security reasons, it will initially be implemented only in `text/html`.
