### ISSUE TITLE
[feature request]allow add custom format

### ISSUE THREAD

**Issue by iamqiz** [asamuzaK/url2clipboard#118]
firstly, thanks for your development of this plugin!
then hope that allow add custom format, so that i can copy text&url in same line or in different line as i like, 
it mean that " copy text&url in same line" and " copy text&url in different line" can occur in right-click menu at the same time
thanks again!💕

**Comment by asamuzaK** [comment]
There are no plans to implement custom formatting.
Different markup languages have different rules for what characters should be escaped or replaced.
It is not as simple as replacing %text% with text and %url% with URL.
See [url2clipboard/format.js#L294](https://github.com/asamuzaK/url2clipboard/blob/master/src/mjs/format.js#L294)
