### ISSUE TITLE
Shortcut not working

### ISSUE THREAD

**Issue by gloomy-ghost** [asamuzaK/url2clipboard#12]
The keyboard shortcut has to be handed in background script in order to work

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/onCommand

**Comment by asamuzaK** [comment]
Not necessary for `_execute_browser_action`.

> _execute_browser_action: works like a click on the add-on's browser action.

[commands - Mozilla | MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Special_shortcuts "commands - Mozilla | MDN")

Confirmed working in Firefox and Chrome, but not in Vivaldi.
Hmm...

**Comment by gloomy-ghost** [comment]
Oops, apparently I didn't try to put the browserAction on the toolbar...
