### ISSUE TITLE
Overlapped links

### ISSUE THREAD

**Issue by itagagaki** [asamuzaK/url2clipboard#120]
Hi,
For the HTML document with the following technique, I found that this add-on does not copy the URL of the link.
Could you manage this?

```
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>test</title>
  </head>
  <body style="background-color:gray;">
    <div style="position:relative;background-color:white;display:inline-block;padding:50px;">
      <a href="link-url" style="position:absolute;top:0;bottom:0;left:0;right:0;"></a>
      <a href="link-url">Anchor Text</a>
    </div>
  </body>
</html>
```

**Comment by asamuzaK** [comment]
What is the expected / actual  result in this case?

**Comment by itagagaki** [comment]
Have you tried it?

expected: link-url
actural: nothing is copied

Probably because the first <a> covers the second <a> and the anchor text is empty.

**Comment by asamuzaK** [comment]
That is not what I get.

Test case 1:
```
    <div style="position:relative;background-color:white;display:inline-block;padding:50px;">
      <a href="link-url" style="position:absolute;top:0;bottom:0;left:0;right:0;"></a>
      <a href="link-url">Anchor Text</a>
    </div>
```

Result (copied as Markdown)
`[file:///C:/Users/XXX/path/to/test/link-url](file:///C:/Users/XXX/path/to/test/link-url)`

Test case 2:
```
    <div style="position:relative;background-color:white;display:inline-block;padding:50px;">
      <a href="https://example.com/foo" style="position:absolute;top:0;bottom:0;left:0;right:0;"></a>
      <a href="https://example.com/bar">Anchor Text</a>
    </div>
```

Result:
`[https://example.com/foo](https://example.com/foo)`

**Comment by asamuzaK** [comment]
Ah, confirmed on Chrome.

**Comment by asamuzaK** [comment]
To be clear, the latter link cannot be selected from the context menu.
This is due to the structure of the HTML and CSS, not because of this extension.
If you want to copy the latter link, you should use tab and move focus, and then use keyboard shortcut.
