### ISSUE TITLE
Support copy all tabs' urls?

### ISSUE THREAD

**Issue by ivysrono** [asamuzaK/url2clipboard#13]
Just like
https://addons.mozilla.org/firefox/addon/firelink/
or
https://addons.mozilla.org/firefox/addon/copy-all-tab-urls-we/

**Comment by asamuzaK** [comment]
There is an add-on for that purpose, and why don't you use that?

**Comment by ivysrono** [comment]
The first is not WebExtension.
The second do not support markdown and BBcode and so on.

**Comment by asamuzaK** [comment]
Why do you need this feature?
I can't imagine the actual use case, please let me know.

**Comment by ivysrono** [comment]
For example, I need to creat lists for debug or describe in github, markdown is the best.

**Comment by asamuzaK** [comment]
OK, got it.

**Comment by asamuzaK** [comment]
Fixed in #17 
Right click on tab.

**Comment by asamuzaK** [comment]
Try build [Copy URL To Clipboard](https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/versions/beta "Copy URL To Clipboard :: Versions :: Add-ons for Firefox")

**Comment by asamuzaK** [comment]
Released [v0.13.1](https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/ "Copy URL To Clipboard :: Add-ons for Firefox")
Context-click on a tab or click toolbar button.
