### ISSUE TITLE
Popup in browser toolbar is no longer working

### ISSUE THREAD

**Issue by grantwinney** [asamuzaK/url2clipboard#130]
Clicking the icon for url2clipboard in the browser toolbar doesn't pop anything up anymore.

I see this in the manifest.json file in your codebase:

```json
  "browser_action": {
    "browser_style": true,
    "default_popup": "html/popup.html",
    "default_icon": "img/icon.svg#current",
    "default_title": "__MSG_extensionName__"
  },
```

But when I look at the source that's out in the Chrome store, I see this... the `default_popup` is missing.

```json
    "browser_action": {
        "browser_style": true,
        "default_icon": {
            "16": "img/icon-outline-16.png",
            "32": "img/icon-outline-32.png"
        },
        "default_title": "__MSG_extensionName__"
    },
```

Do you run a tool against the source code before publishing, and maybe that's causing it?

Nice extension btw, it's very convenient.

**Comment by asamuzaK** [comment]
Released v9.3.1 on Chrome Web Store.
It should be updated after reviewed.

Thanks for your contribution.
