### ISSUE TITLE
Improvement for Text&URL format and few other little things

### ISSUE THREAD

**Issue by maxborowsky** [asamuzaK/url2clipboard#136]
1. It would be good to _optionally_ have blank lines between multiple URLs in the list, for example:

```
DirectX Extensions Viewer | realtech VR
http://www.realtech-vr.com/home/dxview

Geeks3D Free Softwares and Utilities | Geeks3D
https://www.geeks3d.com/softwares/

GPU Caps Viewer: Graphics card and GPU information utility, OpenGL, OpenCL and CUDA API support, NVIDIA GeForce, ATI Radeon | oZone3D.Net
https://ozone3d.net/gpu_caps_viewer/
```
instead
```
DirectX Extensions Viewer | realtech VR
http://www.realtech-vr.com/home/dxview
Geeks3D Free Softwares and Utilities | Geeks3D
https://www.geeks3d.com/softwares/
GPU Caps Viewer: Graphics card and GPU information utility, OpenGL, OpenCL and CUDA API support, NVIDIA GeForce, ATI Radeon | oZone3D.Net
https://ozone3d.net/gpu_caps_viewer/
```

2. It seems to me that there is ambiguity in the names of the menu items. 'Copy Tabs URLs' assumes that the addresses of the **manually selected tabs** will be copied, right? But then why does 'Copy Other Tabs URLs' lead to this result - are the addresses of all tabs copied **except the one** on which I clicked this menu item, **not all except those selected**?

3. The item 'HTML (text/html)' gives exactly the same result as 'Text' - what is their difference?

4. It seems to me that the name of the item 'Copy Link URL' (not the one that appears when you right-click on a link on a web page, but the one that is in the extension menu) should be changed to 'Copy _highlighted_ Link URL', because the item becomes active only if the link is highlighted, but I managed to understand this only experimentally.

As for the rest, I believe that your extension follows Chrome/Firefox visual design guidelines better than similar ones. Thank you for your work!

**Comment by asamuzaK** [comment]
>     2. It seems to me that there is ambiguity in the names of the menu items. 'Copy Tabs URLs' assumes that the addresses of the **manually selected tabs** will be copied, right? But then why does 'Copy Other Tabs URLs' lead to this result - are the addresses of all tabs copied **except the one** on which I clicked this menu item, **not all except those selected**?

Let's track only 1st issue here.
Please file another issue for 2.

>     3. The item 'HTML (text/html)' gives exactly the same result as 'Text' - what is their difference?

Paste it on e.g. Word or Google Docs, then you'll see the difference.

>     4. It seems to me that the name of the item 'Copy Link URL' (not the one that appears when you right-click on a link on a web page, but the one that is in the extension menu) should be changed to 'Copy _highlighted_ Link URL', because the item becomes active only if the link is highlighted, but I managed to understand this only experimentally.

That's not true.
It doesn't need to be highlighted.
Hover mouse on linked text and right click will show 'Copy Link URL' menu.

**Comment by asamuzaK** [comment]
And for the 1st one:

How about insert a blank line when
* `Copy text and URL in separate lines` option enabled
* Copying multiple links with 'Text &amp; URL' from toolbar button

**Comment by maxborowsky** [comment]
@asamuzaK
>**That's not true**

I meant _not this_ menu item

![image](https://user-images.githubusercontent.com/20723033/222588674-2e0fb4b4-e1fa-4bfd-8ac4-0775b0b55d43.png)

but _this one_:

(link in browser is not highlighted)
![image](https://user-images.githubusercontent.com/20723033/222590028-6277d413-3a18-4afd-b1a7-f54ead97e984.png)

(link in browser is highlighted)
![image](https://user-images.githubusercontent.com/20723033/222590125-314bc18b-6577-430b-94d4-9d4cb0fc301c.png)

**Comment by maxborowsky** [comment]
@asamuzaK
> And for the 1st one:
> 
> How about insert a blank line when
> 
> * `Copy text and URL in separate lines` option enabled
> * Copying multiple links with `Text & URL` from toolbar button

Yes, it is for this case that I would like to have empty lines between different links with their descriptions.

**Comment by asamuzaK** [comment]
> but _this one_:
> 
> (link in browser is not highlighted) ![image](https://user-images.githubusercontent.com/20723033/222590028-6277d413-3a18-4afd-b1a7-f54ead97e984.png)
> 
> (link in browser is highlighted) ![image](https://user-images.githubusercontent.com/20723033/222590125-314bc18b-6577-430b-94d4-9d4cb0fc301c.png)

I see.
But if it is not highlighted, the menu is disabled, so I think there is no problem with the current.
Yes, it's a bit confusing, but if we were to change this, we'd have to add a new menu item, which would require additional translations.
I wonder if that much work is necessary.

**Comment by maxborowsky** [comment]
@asamuzaK
>Yes, it's a bit confusing, but if we were to change this, we'd have to add a new menu item, which would require additional translations.

Why add a new item? Why add a new item? Is it not possible to slightly change an existing one? Somehow like this:

![image](https://user-images.githubusercontent.com/20723033/222594639-10b28719-e681-4377-b261-6e46992476f2.png)

And then it will immediately be clear that this is not a strange non-working menu item, but an item that requires a certain preliminary user action.

**Comment by asamuzaK** [comment]
You also need to add localized strings
I can handle en, ja but not zh_CN

**Comment by asamuzaK** [comment]
If you want to eliminate ambiguity, you should consider how to not make it clickable in the first place.
Please no more about this in this issue.
File a new one for it.

**Comment by maxborowsky** [comment]
ОК, thank you for taking the time.

**Comment by asamuzaK** [comment]
Filed #137 for toolbar menu

**Comment by asamuzaK** [comment]
And #138 for 2nd one.

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/url2clipboard/tree/master/dest) with fixes for https://github.com/asamuzaK/url2clipboard/issues/136, https://github.com/asamuzaK/url2clipboard/issues/137, https://github.com/asamuzaK/url2clipboard/issues/138 applied
