### ISSUE TITLE
`Copy Other Tabs URLs` should exclude all selected tabs

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/url2clipboard#138]
Split from #136 
See 2 for detail.

**Comment by maxborowsky** [comment]
I have now manually installed xpi v9.3.3.1 on Firefox, everything is fine, thank you. Is it possible to expect this version in the Chrome Web Store and Firefox Add-ons in the near future?

**Comment by asamuzaK** [comment]
It will be released next week.
