### ISSUE TITLE
Copy as default format by hotkeys directly?

### ISSUE THREAD

**Issue by ivysrono** [asamuzaK/url2clipboard#15]
For example, when press ctrl+u on anywhere, copy as default without click and confirm.

**Comment by asamuzaK** [comment]
It is not worth implementing.
The format which user wants to be "default" varies from user to user.
Even if "default" format is custumizable by user, the desired "default" format also varies from site to site.

**Comment by vegahub** [comment]
This is exactly what I'd need.
A shortcut that would just put current title + URL to clipboard, and a separate one that would do it for links. Or even better if it's conditional. One keyboard shortcut, if there is a link under the cursor copy that, if not copy the current page info. 

Although granted this would need an option to set default format. (or it could just copy all)

This is a feature that I'd use regularly as I used to archive this with two different extention (Copy URL on Mouse Over and Copy Fixer), but they no longer work on 57+ and one of the main reasons I still didn't update, so an implementation would be appreciated. I'd even donate, if you accept bitcoin.

**Comment by asamuzaK** [comment]
As I said above, it's not planned.
You can open a popup with Alt + Shift + C though.
