### ISSUE TITLE
Auto copy selected url adress bar and auto copy selected text inside web pages as plain text 

### ISSUE THREAD

**Issue by trimechee** [asamuzaK/url2clipboard#151]
Hello, thank you so much for this awesome amazing extension which makes our lifes more easy and  comfortable ! 💯  🥇

Please I have request : it will be great to add the ability to automatically copy the selected text inside the press articles into the clipboard as plain text because I do many academic research in many websites and I I often copy extracts and paragraphs from different and variois websites and academic articles and online books and I need to do these copy and paste operations quickly and i need also to copy the source of these articles and I have to quickly copy the url address of found sources and documentation and it will be great if the great Url2clipboard extension can automatically copy the url address of the press articles when we click and select the content of the address bar, thank you a lot !

**Comment by asamuzaK** [comment]
Try using keyboard shortcuts.

[Manage extension shortcuts in Firefox | Firefox Help](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox)

In Chrome, you can do the same from `chrome://extensions/shortcuts`

**Comment by trimechee** [comment]
@asamuzaK Awesome ! Thank you so much for your precious and important recommandaton :) 👍 💯
