### ISSUE TITLE
Copy amo and about: pages by addon bar.

### ISSUE THREAD

**Issue by ivysrono** [asamuzaK/url2clipboard#16]
Just like 
[Copy All Tab Urls WE](https://addons.mozilla.org/firefox/addon/copy-all-tab-urls-we/)
[Format Link](https://addons.mozilla.org/firefox/addon/format-link3/)

**Comment by asamuzaK** [comment]
url2clipboard copies to clipboard in content script.
And content script is disabled in those schemes.

**Comment by ivysrono** [comment]
That is why I open this issue:
![default](https://user-images.githubusercontent.com/2649544/27257661-7d562cde-5411-11e7-967d-86fd2d4190a1.png)

![default](https://user-images.githubusercontent.com/2649544/27257659-60143e04-5411-11e7-9156-3c1126e97b9c.png)

**Comment by asamuzaK** [comment]
Mozilla says content scripts are disabled for security reasons.
I won't hack around to bypass that restriction.
[1310082 - WebExtension content script not working on mozilla.org sites](https://bugzilla.mozilla.org/show_bug.cgi?id=1310082 "1310082 - WebExtension content script not working on mozilla.org sites")

If you want to copy AMO sites, install copy2clipboard in Blink based browsers and then access AMO.

**Comment by gloomy-ghost** [comment]
They don't need to bypass the restriction for content script, as the contextMenus API still works on AMO. 

Bringing back issue #11, my suggestion is that we can enable "copy page URL" on every pages by default and require the content script for enabling "copy link URL". IMHO, a extra row always showing on the contentMenu is less annoying than unable to find it when it's actually needed 😃

**Comment by asamuzaK** [comment]
OK.
I'm working on #13 now.
After that I'll get into this.

**Comment by asamuzaK** [comment]
Partially fixed.
You can not copy from the context menu on restricted sites, but you can copy from the toolbar buttons.

**Comment by asamuzaK** [comment]
Try build [Copy URL To Clipboard](https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/versions/beta "Copy URL To Clipboard :: Versions :: Add-ons for Firefox")

**Comment by asamuzaK** [comment]
I'll work for more when [1272869 - <textarea>.focus() and .select() do not work in background pages](https://bugzilla.mozilla.org/show_bug.cgi?id=1272869 "1272869 - <textarea>.focus() and .select() do not work in background pages") get fixed.

**Comment by asamuzaK** [comment]
Released [v0.13.1](https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/ "Copy URL To Clipboard :: Add-ons for Firefox")

![screenshot](https://user-images.githubusercontent.com/6790339/27426508-e11ff764-5776-11e7-99f2-6c1a99d28c51.png)

**Comment by asamuzaK** [comment]
I'll close this issue.
I've filed #25 as a follow-up.
