### ISSUE TITLE
 [feature request] zim wiki format

### ISSUE THREAD

**Issue by niteria** [asamuzaK/url2clipboard#161]
https://zim-wiki.org/ formats the links with:
```
[[%url%|%content%]]
```

Documentation:
* https://zim-wiki.org/manual/Help/Wiki_Syntax.html#links

This also happens to be the same format as https://www.dokuwiki.org/wiki:syntax#links

I use Zim daily, and I would much appreciate this feature.

**Comment by asamuzaK** [comment]
> Most of this syntax is inspired by the DokuWiki syntax

Is it okay the format name to be `DokuWiki` not `Zim`?

**Comment by asamuzaK** [comment]
Results from [Try pandoc!](https://pandoc.org/try/?text=%5B%5Bhttp%3A%2F%2F%5B%3A%3A1%5D%2F%5D%5BIPv6%5D%5D%0A%0A%5B%5Bhttp%3A%2F%2F%5B%3A%3A1%5D%2F%5D%5D%0A%0A%5B%5Bhttp%3A%2F%2Fexample.com%5D%5Btext+with+brackets+%5B%5D%5D%5D%0A%0A%5B%5Bhttp%3A%2F%2Fexample.com%5D%5Btext+with+escaped+brackets+%5C%5B%5C%5D%5D%5D%0A%0A%5B%5Bhttp%3A%2F%2Fexample.com%5D%5Btext+with+numref+brackets+%26amp;%2391%3B%26amp;%2393%3B%5D%5D%0A&from=org&to=html5)

```
[[http://[::1]/|IPv6]]
[[http://example.com|text with brackets []]]
[[http://example.com|text with escaped brackets \[\]]]
[[http://example.com|text with numref brackets &#91;&#93;]]
```

``` html
<p><a href="http://[::1]/">IPv6</a></p>
<p><a href="http://example.com">text with brackets [</a>]</p>
<p><a href="http://example.com">text with escaped brackets \[\</a>]</p>
<p><a href="http://example.com">text with numref brackets
&amp;#91;&amp;#93;</a></p>
```

**Comment by niteria** [comment]
> > Most of this syntax is inspired by the DokuWiki syntax
> 
> Is it okay the format name to be `DokuWiki` not `Zim`?

Works for me.

**Comment by asamuzaK** [comment]
As you see pandoc results above, DocuWiki (Zim) can not handle brackets, i.e. `[]`, in content text correctly.
So I'm leaving brackets as is.

**Comment by niteria** [comment]
Thank you! Can't wait for the next release :)
