### ISSUE TITLE
FR: copy link + text as ...

### ISSUE THREAD

**Issue by AndyK70** [asamuzaK/url2clipboard#21]
Would be great if you could enhance this extension to copy link + text as html, plain text, BBCode, Wiki-code, Markdown.
That way you would make a 2 step copy+paste to an one step operation. 

Until now it is:

1. copy link as what you need, change to the other tab, where you need it and paste it
2. change back to your source tab, copy link text, change tab again and paste it inside that already pasted link.

It could be:
1.  copy link+text as what you need, change tab where you need it, paste it, done.

**Comment by asamuzaK** [comment]
I don't get what you want.
Are you saying you want to do like below?

Sample HTML:
```
Text for the link.
<a href="exsample.com">link text</a>
```

and you want something like this as a result?
Sample result:
```
<a href="example.com">Text for the link</a>
```

**Comment by asamuzaK** [comment]
If so, try

1. Select "Text for the link"
2. Right click on the anchor element

Selected text will be the content of the link.

**Comment by asamuzaK** [comment]
I waited for over a week, but there isn't any response yet.
If there is additional info, feel free to reopen.
