### ISSUE TITLE
Execute clipboard.js in background

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/url2clipboard#25]
Consider executing clipboard.js in background script.
It can be done when...
* [x] OOP extensions are turned on by default on Linux [Bug 1357487](https://bugzilla.mozilla.org/show_bug.cgi?id=1357487 "1357487 - Turn on OOP extensions by default on Linux")
* [x] OOP extensions are turned on by default on Mac [Bug 1385403](https://bugzilla.mozilla.org/show_bug.cgi?id=1385403 "1385403 - Turn on OOP extensions by default on Mac OS")
* [x] Firefox 60 ESR is out.
* [ ] clipboard.write enabled by default in Firefox [Clipboard.write() - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write)
* [ ] clipboard.write implemented in Chrome [150835 - Support programmatical copying of images to clipboard - chromium - Monorail](https://bugs.chromium.org/p/chromium/issues/detail?id=150835)

Note that `window.prompt` still needs to be executed in content script.

See also [#11](https://github.com/asamuzaK/url2clipboard/issues/11 "Enable on every pages · Issue #11 · asamuzaK/url2clipboard")

**Comment by asamuzaK** [comment]
Note:
Since Firefox 57, popup can be opened from the background too.
See [browserAction.openPopup() - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup "browserAction.openPopup() - Mozilla | MDN")

**Comment by asamuzaK** [comment]
Consider using navigator.clipboard

**Comment by ooker777** [comment]
Why do we need to wait for Mozilla to enable clipboard.write by default? In the page [Clipboard.write()](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write "Clipboard.write() - Web APIs | MDN") it says that you can ask for permission.

**Comment by asamuzaK** [comment]
Because it is still behind pref.
Which means each user needs to enable from about:config.
