### ISSUE TITLE
Lasso

### ISSUE THREAD

**Issue by rayman89** [asamuzaK/url2clipboard#26]
I was wondering if you could implement a lasso like tool (like on windows explorer when you hold left click and drag it to select multiple files) to be able to select the links without having to highlight the text which sometimes gets tricky and bothersome.

**Comment by asamuzaK** [comment]
That feature request is out of the purpose / functionality of this add-on.

You can select link text with Alt + Drag (left click + mouse move), or there seem to be some extensions for that purpose.

* [Select Link Text (Firefox)](https://addons.mozilla.org/en-US/firefox/addon/select-link-text/ "Select Link Text :: Add-ons for Firefox")
* [Drag-Select Link Text (Firefox)](https://addons.mozilla.org/en-US/firefox/addon/drag-select-link-text/ "Drag-Select Link Text :: Add-ons for Firefox")
* [Select like a Boss (Chrome)](https://chrome.google.com/webstore/detail/select-like-a-boss/mnbiiidkialopoakajjpeghipbpljffi "Select like a Boss - Chrome ウェブストア")

**Comment by rayman89** [comment]
What I mean is selection like this outdated addon https://addons.mozilla.org/en-US/firefox/addon/multi-links-plus/

I'm not asking to change the functionality of highlighting text I'm asking if you could change instead of copying the urls that are highlighted to copy the urls that are inside an area.

**Comment by asamuzaK** [comment]
For example, like this?
```
<p>
Some text with a <a href="http://example.com">link to somewhere</a>.
</p>
```
* Select `Some text with a link to somewhere.`
* Right click on `link to somewhere` (anchor element)
* Choose link format
* Then you will get `Some text with a link to somewhere.` as a title of that link

**Comment by asamuzaK** [comment]
If your talking about multiple links support within web page, it's not planned at this moment.

**Comment by rayman89** [comment]
Im talking about  right clicking or key+ left click then dragging the mouse pointer that would create a visible rectangle. When you do that the area inside the rectangle is detected by the addon and then if there are links inside the area then all those links are copied to the clipboard.

**Comment by asamuzaK** [comment]
There seems to be a need for an add-on that enables rectangle selection, but I am not interested in developing it.

As I mentioned earlier, there is no plan to implement copy multiple links within a page, at this point.

Picking up *all* links and copying is easy.
However, I think it is useless, I think that you would want to copy a certain link but want to exclude another.
Then,

* For example, let's say there is a menu "Copy multiple links in the selection range"
* Ask user to select a format (HTML, Markdown and so on)
* Show candidate list of links to be copied, ask user to choose which one to copy and not to copy. 
  Note that this list can be very long depending on user's selection
* Show corrected candidate list, let user can go back and select again

Like this, it is unlikely that the UI will be complicated.

**Comment by asamuzaK** [comment]
How about this add-on?
[Snap Links Plus :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/ "Snap Links Plus :: Add-ons for Firefox")

**Comment by asamuzaK** [comment]
Sorry, but out of purpose.
Close this issue.
