### ISSUE TITLE
Provide features like Easy Copy did.

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [asamuzaK/url2clipboard#27]
Another overnight-obsoleted extension is [Easy Copy](https://addons.mozilla.org/en-US/firefox/addon/easy-copy/?src=search). 

Easy Copy has been on my shortlist of best extensions for years

It has a simple yet very flexible configuration system which basically allows you to generated whatever markup language you need, while supporting many uses cases. Examples:

* don't select anything, copy -> becomes link to the page, with page title as link text
* _select any snippet of text in the page_, copy -> becomes link to the page, with the text you selected as link text _<<== the one I use most_
* don't select anything, right-click on link, copy -> same result as precisely selecting the link and copying it, just much easier
* the simple and powerful configuration options allow to provide the behavior of [CoLT](https://addons.mozilla.org/en-US/firefox/addon/colt/).
* copy all tabs as links (all this, whatever markup language)

## Screenshots

![use](https://addons.cdn.mozilla.net/user-media/previews/full/124/124227.png?modified=1419676255)

![configuration](https://addons.cdn.mozilla.net/user-media/previews/full/148/148910.png?modified=1419676255)

## Conclusion

* Praise "url-to-clipboard" for being compatible with Firefox 57+!
* I guess it can technically be extended to support all this. If would be soo great!

**Comment by asamuzaK** [comment]
> * don't select anything, copy -> becomes link to the page, with page title as link text

url2clipboard does so.

> * select any snippet of text in the page, copy -> becomes link to the page, with the text you selected as link text <<== the one I use most

url2clipboard does so.

> * don't select anything, right-click on link, copy -> same result as precisely selecting the link and copying it, just much easier

url2clipboard does so.
Plus, if you select some text, that text will be the content of the link.

> * the simple and powerful configuration options allow to provide the behavior of CoLT.

I don't have a plan to make format templates customizable at the moment.
If customization is absolutely necessary, I recommend using other add-on. For example, [Format Link](https://addons.mozilla.org/en-US/firefox/addon/format-link3/ "Format Link – Add-ons for Firefox")

If you want to add a new format that is not in the current format list, please submit a feature request of that format.

> * copy all tabs as links (all this, whatever markup language)

url2clipboard does so.

**Comment by asamuzaK** [comment]
> * copy all tabs as links (all this, whatever markup language)

url2clipboard does so, but only from the toolbar button.

**Comment by fidergo-stephane-gourichon** [comment]
> url2clipboard does so.

Ah, thanks! I missed some facts. The popup that appears to ask link text actually offers by default the expected text. And it can be disabled with configuration!

> If customization is absolutely necessary, I recommend using other add-on. For example, Format Link

Thanks! I tried that extension. Language seems powerful (and complicated :-). 

> url2clipboard does so, but only from the toolbar button.

Great!

Only, in some cases the "Copy Page URL" appears in context menu but greyed out and unselectable. If I find a pattern I consider writing a bug report.

> If you want to add a new format that is not in the current format list, please submit a feature request of that format.

Okay.

**Comment by asamuzaK** [comment]
Oh, maybe I misread what you meant.
Did you mean to add each context menu like "Copy" "Copy Title Link" and so on?
If so, it's not planned.
Such a context menu seems too complicated.

**Comment by asamuzaK** [comment]
> Only, in some cases the "Copy Page URL" appears in context menu but greyed out and unselectable. If I find a pattern I consider writing a bug report.

In about: urls and/or pages in addons.mozilla.org, they are grayed out.
That's WebExtensions limitation.

**Comment by fidergo-stephane-gourichon** [comment]
I didn't ask for "Copy Title Link" explicit menus. This seems redundant once user knows what's possible. Your extension feels actually simpler and more straightforward that the old Easy Copy now. :-)

Regarding the bug, it happened on this very page while I was editing text. At some moments the menu item was greyed out, at other moments it worked. Now it works.

> If you want to add a new format that is not in the current format list, please submit a feature request of that format.

Done so. Cheers!
https://github.com/asamuzaK/url2clipboard/issues/28
https://github.com/asamuzaK/url2clipboard/issues/29

**Comment by asamuzaK** [comment]
> Regarding the bug, it happened on this very page while I was editing text. At some moments the menu item was greyed out, at other moments it worked. Now it works.

When that happens, reload the page and then context menu will get live again.

**Comment by asamuzaK** [comment]
One note about copy all tabs URL, you can do that by right clicking on tab too.
I forgot about that...
It is available only in Gecko browsers. 
Blink browsers does not support tab context menu.
