### ISSUE TITLE
Support textile format.

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [asamuzaK/url2clipboard#28]
It would be nice to support Textile markup links.
See https://txstyle.org/doc/12/links

Cheers!

**Comment by asamuzaK** [comment]
Bug in textile?
When I was testing some cases in https://txstyle.org/doc/12/links

```
"parens in content &#x28;and title&#x29;(&#x28;example.com&#x29;)":http://example.com/
"quotes in content &quot;and title&quot;(&quot;example.com&quot;)":http://example.com/
```

Those result as
```
<a href="http://example.com/" title="&amp;#x28;example.com&amp;#x29;">parens in content &#x28;and title&#x29;</a>
<a href="http://example.com/" title="&amp;quot;example.com&amp;quot;">quotes in content &quot;and title&quot;</a>
```

"&" chars in title are unnecessarily converted.

**Comment by fidergo-stephane-gourichon** [comment]
## Reproduced

I could reproduce what you wrote, on https://txstyle.org/doc/12/links with a copy-paste of your two lines then press "Send".

## Is feature really needed?

It looks like link text with title is an uncommon textile syntax. Actually I did not know it. 

According to [Textile (markup language) - Wikipedia](https://en.wikipedia.org/wiki/Textile_(markup_language)#Standardization "Textile (markup language) - Wikipedia"), "There is no standard nor a working specification at this time. However, there is a Textile "organization" on GitHub that invites contributions toward the creation of a common specification across Textile implementations.[11]"

Link title *is* mentioned on tentative common spec, see https://github.com/textile/textile-spec/blob/master/phrase_modifiers.yaml#L78

## Not universally supported anyway

Pandoc does not seem to support link title, see below.

```
{ echo '"parens in content &#x28;and title&#x29;(&#x28;example.com&#x29;)":http://example.com/' ; echo '"quotes in content &quot;and title&quot;(&quot;example.com&quot;)":http://example.com/' ; } | pandoc  -i /dev/stdin -f textile -t html

<p><a href="http://example.com/">parens in content (and title)((example.com))</a><br />
<a href="http://example.com/">quotes in content &quot;and title&amp;quot;(&quot;example.com&amp;quot;)</a></p>
```

## Conclusion

I didn't expect url2clipboard to worry about custom link title. :-)

Yet I would consider that you're right: the strange behavior is probably a bug on the engine that runs https://txstyle.org/ .

I think we can safely ignore the bug. Even consider it a hint that the feature implemented is not something many people care about. Perhaps report it to authors there.

Another thing worried me for a moment: what to do when selected text does include parens?
You already went the right way IMHO: you escaped parens in link text, so you alwats get a safe link that works in all implementations.

Cheers!

**Comment by asamuzaK** [comment]
> It looks like link text with title is an uncommon textile syntax. Actually I did not know it.

I'll ignore title then.

**Comment by asamuzaK** [comment]
Fixed. (not released yet)

**Comment by asamuzaK** [comment]
Try build [v0.18.0a2](https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/versions/beta)

**Comment by fidergo-stephane-gourichon** [comment]
Tested briefly, v0.18.0a2 is fine regarding this topic.
