### ISSUE TITLE
Link to be pasted into a HTML document

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [asamuzaK/url2clipboard#30]
I expected HTML output to be pastable into a HTML document, e.g. in Thunderbird.
Hence this enhancement request (which borrows the structure of a bug report).

# How to reproduce

* Either select some text, or nothing.
* Right click on tab, or on page area.
* In context menu, select an output format. Let's call it "pastable link" here.
* Go to a Thunderbird write message window.
* Trigger paste feature (either Ctrl-V or context menu).

# Expected

* A link is inserted into the document with some text and destination URL.

# Observed

* No "pastable link" output format.
* With HTML output format, HTML source _code_ of a link is inserted (`<a href="URL">text</a>`) instead or a clickable link with text and expected destination URL.

# Platform

* Xorg windowing system (more precisely, Ubuntu Linux 16.04 AMD64 running XFCE).
* Firefox 57.
* Thunderbird (any version).

**Comment by fidergo-stephane-gourichon** [comment]
For complete information, Easy Copy includes a "Type" dropbox and a checkbox "Format for HTML" which IIRC is related to this.

![Easy Copy configuration](https://addons.cdn.mozilla.net/user-media/previews/full/148/148910.png?modified=1419676255)

**Comment by asamuzaK** [comment]
Select link text, copy it (Ctrl + C) and paste (Ctrl + V) on your document.
You can do it without an add-on?

**Comment by asamuzaK** [comment]
Ah, but you can't do that for document URL.

**Comment by fidergo-stephane-gourichon** [comment]
> Ah, but you can't do that for document URL.

Indeed.

# Other scenarii: url2clipboard much more convenient

* Source of URL can be page (tab) title.
    * Without extension: 
        * Open go to page source code (only way to access title as selectable text)
        * find title element, see if readable in spite of [HTML entities](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references) (lots of accents in French)
        * manually select text among HTML markup, copy
        * go to destination document, there paste as unformatted text
        * clean up text by manually decoding HTML entities (lots of accents in French)
        * back to page, manually copy the URL (of current tab or link destination)
        * back to destination document, open the feature that allows to create a new link (Ctrl-K in Thunderbird IIRC)
        * paste the URL in "new link" dialog
    * With url2clopboard -> right click on tab, select destination format, paste. Done!
* Source of text can be any text on the page. 
    * Without extension: 
        * select text in source page,
        * go to destination document, there paste _as unformatted text_
        * manually copy the URL (of current tab or link destination)
        * open the feature that allows to create a new link (Ctrl-K in Thunderbird IIRC)
        * paste the URL in "new link" dialog
    * With url2clopboard -> select text, right click on tab or link, choose destination format, paste. Done!

# More antifeatures of link copy-paste without add-on

Even in the case you mention (just select link):

* The selected link itself sometimes has extra formatting or is inside some paragraph/div/table cell/header, has CSS class, font, whatever. Those are no more welcome in the destination document than they would be in a markup document.
* On some pages it isn't even practical to select a link: sometimes it is surrounded by other elements or without easy-to-select boundaries. You then select unwanted surrounding page elements, including paragraph separators, table cells, div, headers and whatnot, that you have to cleanup in destination document.
* Trying to select only the whole link text or part of it actually starts a drag-and-drop, so it just does not work. 

# Conclusion

Some benefits of url2clipboard are:

* it just creates a plain link without any formatting or unwanted stuff
* it is flexible regarding text to be used as link and destination URL
* it requires few actions

Those benefits are fully valid even when the destination document is HTML like the original document, because we don't want the original HTML, just a plain link.

**Comment by asamuzaK** [comment]
Try build [v0.18.0a2](https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/versions/beta)
