### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by mwoffenden** [asamuzaK/url2clipboard#35]
sorry please delete posted in error.

**Comment by asamuzaK** [comment]
It does. I created the below link with this add-on.
```
<a href="https://github.com/asamuzaK/url2clipboard/issues/35" title="Does not work · Issue #35 · asamuzaK/url2clipboard">Does not work · Issue #35 · asamuzaK/url2clipboard</a>
```

> Trying to copy page URL as HTML, it does nothing!

What do you want me to do with just this information?
