### ISSUE TITLE
Need format for JIRA

### ISSUE THREAD

**Issue by mwoffenden** [asamuzaK/url2clipboard#37]
JIRA wants URLs in this format: [link title|http://example.com]

Could this be added to the tool?

**Comment by asamuzaK** [comment]
Can you show me some documents I can refer to?

**Comment by mwoffenden** [comment]
Does this help?  

[Text Formatting Notation Help - Create and track feature requests for Atlassian products.](https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=links "Text Formatting Notation Help - Create and track feature requests for Atlassian products.")

**Comment by asamuzaK** [comment]
Thanks.
Can you tell me how JIRA converts these samples?

* `[text containing brackets []|http:example.com]`
* `[text containing brackets \[\]|http:example.com]`
* `[text containing brackets &#91;&#93;|http:example.com]`
* `[text containing pipe ||http:example.com]`
* `[text containing pipe \||http:example.com]`
* `[text containing pipe &#124;|http:example.com]`
* `[IPv6|http://[::1]/]`

**Comment by mwoffenden** [comment]
Unfortunately I have no idea.   I'm just a user of JIRA.

**Comment by asamuzaK** [comment]
Paste above codes in JIRA's comment area and tell me results?

**Comment by mwoffenden** [comment]
Here's the comment in JIRA:

<img width="329" alt="screenshot_1107" src="https://user-images.githubusercontent.com/6774346/34682015-978bd130-f46b-11e7-9eb0-1a37600ac46e.png">

**Comment by asamuzaK** [comment]
Is this a screenshot after posting a comment?

**Comment by mwoffenden** [comment]
Yes.

**Comment by asamuzaK** [comment]
* `[link text|http://example.com]`

This is properly converted to a link, right?

I can not understand why all samples are treated as just plain text.
I expected that the 3rd and 6th would be converted into links properly.

**Comment by mwoffenden** [comment]
Yes, your above text works correctly.

<img width="537" alt="screenshot_1109" src="https://user-images.githubusercontent.com/6774346/34722765-24d7b004-f516-11e7-94f7-895a87902119.png">

**Comment by asamuzaK** [comment]
Then I'll leave link text as is.
By the way, "JIRA" and "Jira", which is more common?

**Comment by mwoffenden** [comment]
Jira - See: https://www.atlassian.com/software/jira

**Comment by asamuzaK** [comment]
Thanks, I'll get into this.

**Comment by asamuzaK** [comment]
Try build
[Copy URL To Clipboard :: Versions :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/versions/beta "Copy URL To Clipboard :: Versions :: Add-ons for Firefox")

**Comment by mwoffenden** [comment]
Works great!  Jira users will love this.

<img width="536" alt="screenshot_1110" src="https://user-images.githubusercontent.com/6774346/34726007-be6ea0e2-f520-11e7-8e89-2dcdd8ed5932.png">

**Comment by asamuzaK** [comment]
Released [v1.1.0](https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/ "Copy URL To Clipboard – Add-ons for Firefox")
Note that Beta version will not update automatically.
You need to install Release version again.
