### ISSUE TITLE
it does not work in latest firefox

### ISSUE THREAD

**Issue by i5on9i** [asamuzaK/url2clipboard#45]
OS : windows 10
Web browser : Firefox Quantum 59.0.2(64bit)

Hi,

I like this extension but it starts not to work from the v59.0.2 of the firefox quantum
If you have any help, please let me know.

Anyway, thanks for your work of this great extension.

**Comment by asamuzaK** [comment]
Dupe #46

**Comment by asamuzaK** [comment]
It was a regression.
Sorry for the bug.

You can download v1.3.1 on AMO.
