### ISSUE TITLE
chrome 66 cannot work

### ISSUE THREAD

**Issue by leeyaunlong** [asamuzaK/url2clipboard#46]
I installed it from google webstore. I also enabled it.
But it cannot copy any thing.
I can saw the grey status with toolbar icon or right menu list.

**Comment by asamuzaK** [comment]
Confirmed.
Give me some time to inspect.

**Comment by asamuzaK** [comment]
It was a regression.
Sorry for the bug.

v1.3.1 will be released shortly.

Thanks for the report.
