### ISSUE TITLE
Please make a BBCode option.

### ISSUE THREAD

**Issue by streetwolf** [asamuzaK/url2clipboard#5]
This is need for things like forums.  Please consider it.

**Comment by asamuzaK** [comment]
```
[url=http://example.com/]Document Title[/url]
```
Like this?

**Comment by streetwolf** [comment]
Yes, like your example.  Also an entry to copy the url of the current page would be nice.  If you look at the now unsupported add-on COLT you will see what it does to give you some ideas.

**Comment by asamuzaK** [comment]
Try https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/versions/beta

**Comment by streetwolf** [comment]
Example... I go to a forum that accepts BBCode.  I click on a link and select one of the BBCode options.  I place it into a Reply/Comment box. I then preview it.  Instead of going to the link I copied I go to the same page I was on.  In otherwords all the BBCode options are just creating a link to the page, not to any links within the page.

**Comment by asamuzaK** [comment]
You mean
```
<a href="http://example.com">link to example.com</a>
```
and you want
```
[url=http://example.com]link to example.com[/url]
```
or
```
[url]http://example.com[/url]
```
as a result?

**Comment by streetwolf** [comment]
Maybe I'm not understanding how your add-on works.  It appears that selecting any type of URL format from your context menu just gets you to the page where you selected the URL.   If I click on a link within the page the URL created should be of that link and take me there not the page where the link was.

Example...  Go to Wikipedia.  Bring up your menu on a link within an article or main page.  Select any type of URL format.  Paste the URL somewhere and notice it is a link for the page where the link was not the link itself.

If all your add-on is doing is providing different format links for the page you are on it is very limited IMO and isn't of much use to me.  Again, look at COLT and see how it handles links.

**Comment by asamuzaK** [comment]
Ah, got it.
This add-on is on going one and unstable yet, I have only implemented my use case.
Which is copy document Title (or selected text) and URL of that page.
A link within that page is not supported.
I'll file another issue for that.

**Comment by streetwolf** [comment]
As I mentioned, the now unsupported add-on CoLT handled every possible link/url situation.  The developer doesn't want to bother changing his add-on to support WebExtensions.  

I don't know how you feel about taking over someone else's work but perhaps recoding CoLT  for WE is not that time consuming assuming the developer is willing to give it up to you.

You can find CoLT here.... https://addons.mozilla.org/en-US/firefox/addon/colt/?src=ss

**Comment by asamuzaK** [comment]
It's not about BBCode anymore.
Let's continue in #6
