### ISSUE TITLE
Add option to only assign only one URL to button

### ISSUE THREAD

**Issue by jmozmoz** [asamuzaK/url2clipboard#50]
Would it be possible to assign only one URL function to the toolbar button, e.g. Text URL without any submenues. Or one entry in the context menu, to directly copy one of the possible URL/Title/format strings.

If possible, it should be possible to choose this in the addon settings (e.g. if all but one of the formats are disabled)

**Comment by jmozmoz** [comment]
> Can you clarify in more detail?
If you deselect all but one encoding for the current page URL in the preferences, the popup menu contains an item Copy Page URL with a sub-menu, e.g. Text. My suggestions is: If only one encoding is enabled, change the entry in the popup menu to something like "Copy Page URL as Text" without a sub-menu.

**Comment by asamuzaK** [comment]
> If you deselect all but one encoding for the current page URL in the preferences, the popup menu contains an item Copy Page URL with a sub-menu, e.g. Text. My suggestions is: If only one encoding is enabled, change the entry in the popup menu to something like "Copy Page URL as Text" without a sub-menu.

Filed #53 for that

**Comment by asamuzaK** [comment]
Fixed #53 
Try build available [url2clipboard/dest at master · asamuzaK/url2clipboard](https://github.com/asamuzaK/url2clipboard/tree/master/dest "url2clipboard/dest at master · asamuzaK/url2clipboard")

**Comment by jmozmoz** [comment]
I used your test build and it works as expected. Thank you for your fast response.
