### ISSUE TITLE
Site URL part not correctly copied from heise.de

### ISSUE THREAD

**Issue by jmozmoz** [asamuzaK/url2clipboard#51]
If I use the addon to copy the Text URL to the clippboard, the site URL part is missing:

So, e.g. for this page 
https://www.heise.de/newsticker/meldung/Auffahrunfaelle-an-neuen-Mautstationen-4097443.html the following is copied to the clipboard:
Auffahrunfälle an neuen Mautstationen | heise online /newsticker/meldung/Auffahrunfaelle-an-neuen-Mautstationen-4097443.html

**Comment by asamuzaK** [comment]
Fixed.
v1.5.2 should be released soon.
