### ISSUE TITLE
Add ability to copy a link within the page

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/url2clipboard#6]
See #5

**Comment by asamuzaK** [comment]
Try build https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/versions/beta

**Comment by streetwolf** [comment]
Most of the options are not working correctly with this version.  The only one that seems to work is the text options.  The HTML and BBCode do not have their corresponding tags on the link.  Furthermore nothing is going to my clipboard so there is nothing to paste.

-----
Gary

**Comment by asamuzaK** [comment]
Really?
It's working on my Win10 + Nightly though.

Can you give me info about your environment?
OS, Firefox version, etc.

**Comment by asamuzaK** [comment]
Oh, confirmed.
Maybe I missed something.

**Comment by streetwolf** [comment]
Once you get the problems fixed may I suggest that if you right click on a link there is no reason to show the page link option.  Same goes if you right click on something other than a link there is no reason to see the link options.  Unless Webextensions doesn’t permit it the add-on should know if it’s a link or a page link and only show the corresponding options.

-----
Gary

**Comment by asamuzaK** [comment]
Updated
Try build https://addons.mozilla.org/en-US/firefox/addon/url2clipboard/versions/beta

**Comment by asamuzaK** [comment]
> I suggest that if you right click on a link there is no reason to show the page link option.

That's restriction in WebExtension's contextMenus API.
Something like "all" but not "link" is not available.

**Comment by streetwolf** [comment]
Same issues as before.  I disabled all my add-ons except for yours.  Here’s my specs from about:support.

Application Basics
Name

Firefox

Version

55.0a1

Build ID

20170515033002

Update History

Show Update History

Update Channel

default

User Agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

OS

Windows_NT 10.0

Profile Folder

Open Folder

Enabled Plugins

about:plugins

Build Configuration

about:buildconfig

Memory Use

about:memory

Performance

about:performance

Registered Service Workers

about:serviceworkers

Multiprocess Windows

1/1 (Enabled by user)

Google Key

Found

Mozilla Location Service Key

Found

Safe Mode

false

Profiles

about:profiles

Crash Reports for the Last 3 Days
Report ID

Submitted


All Crash Reports<about:crashes>

This application has not been configured to display crash reports.

Nightly Features
Name

Version

ID

Activity Stream

0.0.0

activity-stream@mozilla.org

Application Update Service Helper

2.0

aushelper@mozilla.org

Firefox Screenshots

6.6.0

screenshots@mozilla.org

FlyWeb

1.0.0

flyweb@mozilla.org

Form Autofill

1.0

formautofill@mozilla.org

Multi-process staged rollout

1.50

e10srollout@mozilla.org

Pocket

1.0.5

firefox@getpocket.com

Presentation

1.0.0

presentation@mozilla.org

Shield Recipe Client

51

shield-recipe-client@mozilla.org

Web Compat

1.1

webcompat@mozilla.org

WebCompat Reporter

1.0.0

webcompat-reporter@mozilla.org

Extensions
Name

Version

Enabled

ID

AutoplayStopper

0.9.7

true

ejddcgojdblidajhngkogefpkknnebdh@chrome-store-foxified-3264070466

Better Image Viewer

14

true

betterimageviewer@darktrojan.net

Cookie AutoDelete

1.2.0

true

CookieAutoDelete@kennydo.com

Copy URL To Clipboard

0.11.0a3

true

url2clipboard@asamuzak.jp

Font Finder

0.1.7

true

{a658a273-612e-489e-b4f1-5344e672f4f5}

History Cleaner

1.2.2

true

{a138007c-5ff6-4d10-83d9-0afaf0efbe5e}

LastPass: Free Password Manager

5.1.1

true

support@lastpass.com

Magic Actions for YouTube™

6.9.1.2

true

jid0-UVAeBCfd34Kk5usS8A1CBiobvM8@jetpack

uBlock Origin/webext

1.12.4

true

uBlock0-webext@raymondhill.net

Zoom Page WE

5.1

true

zoompage-we@DW-dev

Graphics
Features

Compositing

Direct3D 11

Asynchronous Pan/Zoom

wheel input enabled; scrollbar drag enabled

WebGL 1 Driver WSI Info

EGL_VENDOR: Google Inc. (adapter LUID: 000000000000912c) EGL_VERSION: 1.4 (ANGLE 2.1.0.dec065540d5f) EGL_EXTENSIONS: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_stream_producer_d3d_texture_nv12 EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle EGL_ANGLE_platform_angle_d3d EGL_ANGLE_device_creation EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path EGL_KHR_client_get_all_proc_addresses

WebGL 1 Driver Renderer

Google Inc. -- ANGLE (AMD Radeon (TM) R9 390 Series Direct3D11 vs_5_0 ps_5_0)

WebGL 1 Driver Version

OpenGL ES 2.0 (ANGLE 2.1.0.dec065540d5f)

WebGL 1 Driver Extensions

GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_pack_reverse_row_order GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object

WebGL 1 Extensions

ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_shader_texture_lod EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc MOZ_WEBGL_depth_texture

WebGL 2 Driver WSI Info

EGL_VENDOR: Google Inc. (adapter LUID: 000000000000912c) EGL_VERSION: 1.4 (ANGLE 2.1.0.dec065540d5f) EGL_EXTENSIONS: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_stream_producer_d3d_texture_nv12 EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle EGL_ANGLE_platform_angle_d3d EGL_ANGLE_device_creation EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path EGL_KHR_client_get_all_proc_addresses

WebGL 2 Driver Renderer

Google Inc. -- ANGLE (AMD Radeon (TM) R9 390 Series Direct3D11 vs_5_0 ps_5_0)

WebGL 2 Driver Version

OpenGL ES 3.0 (ANGLE 2.1.0.dec065540d5f)

WebGL 2 Driver Extensions

GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_pack_reverse_row_order GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object

WebGL 2 Extensions

EXT_color_buffer_float EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc

Audio Backend

wasapi

Direct2D

true

DirectWrite

false (10.0.15063.0)

GPU #1

Active

Yes

Description

AMD Radeon (TM) R9 390 Series

Vendor ID

0x1002

Device ID

0x67b1

Driver Version

22.19.165.1

Driver Date

5-2-2017

Drivers

aticfx64 aticfx64 aticfx64 amdxc64 aticfx32 aticfx32 aticfx32 amdxc32 atiumd64 atidxx64 atidxx64 atiumdag atidxx32 atidxx32 atiumdva atiumd6a atitmm64

Subsys ID

00000000

RAM

8192

GPU #2

Diagnostics

ClearType Parameters

DISPLAY1 [ Gamma: 2.2 Pixel Structure: RGB ClearType Level: 0 Enhanced Contrast: 100 ] DISPLAY2 [ Gamma: 2.2 Pixel Structure: RGB ClearType Level: 0 Enhanced Contrast: 100 ]

AzureCanvasAccelerated

0

AzureCanvasBackend

Direct2D 1.1

AzureCanvasBackend (UI Process)

cairo

AzureContentBackend

Direct2D 1.1

AzureContentBackend (UI Process)

cairo

AzureFallbackCanvasBackend (UI Process)

skia

GPUProcessPid

1348

GPUProcess

Terminate GPU Process

ClearType Parameters

DISPLAY1 [ Gamma: 2.2 Pixel Structure: RGB ClearType Level: 0 Enhanced Contrast: 100 ] DISPLAY2 [ Gamma: 2.2 Pixel Structure: RGB ClearType Level: 0 Enhanced Contrast: 100 ]

Decision Log

WEBRENDER

opt-in by default: WebRender is an opt-in feature


Crash Guard Disabled Features

Workarounds

Failure Log

Important Modified Preferences
Name

Value

accessibility.typeaheadfind

true

accessibility.typeaheadfind.flashBar

0

browser.cache.disk_cache_ssl

false

browser.cache.disk.capacity

358400

browser.cache.disk.filesystem_reported

1

browser.cache.disk.hashstats_reported

1

browser.cache.disk.parent_directory

D:\

browser.cache.disk.smart_size.first_run

false

browser.cache.disk.smart_size.use_old_max

false

browser.cache.frecency_experiment

3

browser.cache.memory.capacity

-1

browser.display.document_color_use

1

browser.display.show_image_placeholders

false

browser.download.folderList

2

browser.download.importedFromSqlite

true

browser.download.manager.addToRecentDocs

false

browser.fixup.dns_first_for_single_words

true

browser.link.open_newwindow

1

browser.link.open_newwindow.restriction

0

browser.places.smartBookmarksVersion

8

browser.search.openintab

true

browser.search.update

false

browser.search.useDBForOrder

true

browser.sessionstore.privacy_level

2

browser.sessionstore.resume_from_crash

false

browser.sessionstore.upgradeBackup.latestBuildID

20170515033002

browser.startup.homepage

about:home

browser.startup.homepage_override.buildID

20170515033002

browser.startup.homepage_override.mstone

55.0a1

browser.tabs.closeWindowWithLastTab

false

browser.tabs.crashReporting.includeURL

true

browser.tabs.loadBookmarksInBackground

true

browser.tabs.loadInBackground

false

browser.tabs.remote.autostart

true

browser.tabs.remote.autostart.2

false

browser.tabs.showAudioPlayingIcon

false

browser.tabs.warnOnClose

false

browser.tabs.warnOnCloseOtherTabs

false

browser.urlbar.clickSelectsAll

false

browser.urlbar.doubleClickSelectsAll

true

browser.urlbar.oneOffSearches

false

browser.urlbar.searchSuggestionsChoice

false

browser.urlbar.suggest.bookmark

false

browser.urlbar.suggest.openpage

false

browser.urlbar.unifiedcomplete

false

browser.urlbar.usepreloadedtopurls.enabled

false

browser.urlbar.userMadeSearchSuggestionsChoice

true

dom.apps.lastUpdate.buildID

20160725043120

dom.apps.lastUpdate.mstone

50.0a1

dom.apps.reset-permissions

true

dom.audiochannel.audioCompeting

true

dom.battery.enabled

false

dom.dialog_element.enabled

true

dom.disable_beforeunload

true

dom.event.clipboardevents.enabled

false

dom.experimental_forms

true

dom.forms.datetime

true

dom.forms.datetime.timepicker

true

dom.gamepad.extensions.enabled

true

dom.image.picture.enabled

true

dom.image.srcset.enabled

true

dom.input.dirpicker

true

dom.ipc.plugins.asyncInit.enabled

true

dom.mozApps.used

true

dom.popup_maximum

5

dom.push.userAgentID

120774746a58434ab3b2dd2726bf0a21

dom.vibrator.enabled

false

dom.webcomponents.customelements.enabled

true

dom.webcomponents.enabled

true

extensions.lastAppVersion

55.0a1

font.internaluseonly.changed

true

font.name.monospace.x-western

Fixedsys

font.name.sans-serif.x-western

Liberation Sans

font.name.serif.x-western

Liberation Sans

font.size.fixed.x-western

16

gfx.canvas.azure.backends

direct2d1.1,cairo,skia

gfx.content.azure.backends

direct2d1.1,cairo,skia

media.benchmark.vp9.fps

338

media.benchmark.vp9.versioncheck

2

media.ffmpeg.enabled

true

media.gmp-eme-adobe.enabled

true

media.gmp-eme-adobe.lastUpdate

1457527936

media.gmp-eme-adobe.version

17

media.gmp-gmpopenh264.abi

x86_64-msvc-x64

media.gmp-gmpopenh264.enabled

true

media.gmp-gmpopenh264.lastUpdate

1471452515

media.gmp-gmpopenh264.version

1.6

media.gmp-manager.buildID

20170515033002

media.gmp-manager.lastCheck

1494856197

media.gmp-widevinecdm.abi

x86_64-msvc-x64

media.gmp-widevinecdm.lastUpdate

1470698764

media.gmp-widevinecdm.version

1.4.8.903

media.gmp.decoder.enabled

true

media.gmp.storage.version.observed

1

media.hardware-video-decoding.failed

false

media.mediasource.webm.enabled

true

media.navigator.video.default_fps

60

media.navigator.video.default_minfps

30

media.peerconnection.ice.proxy_only

true

media.webrtc.debug.aec_log_dir

d:\temp

media.webrtc.debug.log_file

d:\temp\WebRTC.log

media.webspeech.recognition.enable

true

mousewheel.acceleration.start

1

network.cookie.cookieBehavior

1

network.cookie.lifetime.days

9999

network.cookie.prefsMigrated

true

network.http.max-persistent-connections-per-server

18

network.predictor.cleaned-up

true

network.warnOnAboutNetworking

false

places.database.lastMaintenance

1494508886

places.history.expiration.transient_current_max_pages

62108

plugin.disable_full_page_plugin_for_types

application/pdf

plugin.importedState

true

plugins.click_to_play

false

print.printer_Brother_MFC-J475DW_Printer.print_bgcolor

false

print.printer_Brother_MFC-J475DW_Printer.print_bgimages

false

print.printer_Brother_MFC-J475DW_Printer.print_duplex

-437918235

print.printer_Brother_MFC-J475DW_Printer.print_edge_bottom

0

print.printer_Brother_MFC-J475DW_Printer.print_edge_left

0

print.printer_Brother_MFC-J475DW_Printer.print_edge_right

0

print.printer_Brother_MFC-J475DW_Printer.print_edge_top

0

print.printer_Brother_MFC-J475DW_Printer.print_evenpages

true

print.printer_Brother_MFC-J475DW_Printer.print_footercenter

print.printer_Brother_MFC-J475DW_Printer.print_footerleft

&PT

print.printer_Brother_MFC-J475DW_Printer.print_footerright

&D

print.printer_Brother_MFC-J475DW_Printer.print_headercenter

print.printer_Brother_MFC-J475DW_Printer.print_headerleft

&T

print.printer_Brother_MFC-J475DW_Printer.print_headerright

&U

print.printer_Brother_MFC-J475DW_Printer.print_in_color

true

print.printer_Brother_MFC-J475DW_Printer.print_margin_bottom

0.5

print.printer_Brother_MFC-J475DW_Printer.print_margin_left

0.5

print.printer_Brother_MFC-J475DW_Printer.print_margin_right

0.5

print.printer_Brother_MFC-J475DW_Printer.print_margin_top

0.5

print.printer_Brother_MFC-J475DW_Printer.print_oddpages

true

print.printer_Brother_MFC-J475DW_Printer.print_orientation

0

print.printer_Brother_MFC-J475DW_Printer.print_page_delay

50

print.printer_Brother_MFC-J475DW_Printer.print_paper_data

1

print.printer_Brother_MFC-J475DW_Printer.print_paper_height

11.00

print.printer_Brother_MFC-J475DW_Printer.print_paper_name

print.printer_Brother_MFC-J475DW_Printer.print_paper_size_unit

0

print.printer_Brother_MFC-J475DW_Printer.print_paper_width

8.50

print.printer_Brother_MFC-J475DW_Printer.print_resolution

600

print.printer_Brother_MFC-J475DW_Printer.print_reversed

false

print.printer_Brother_MFC-J475DW_Printer.print_scaling

1.00

print.printer_Brother_MFC-J475DW_Printer.print_shrink_to_fit

true

print.printer_Brother_MFC-J475DW_Printer.print_to_file

false

print.printer_Brother_MFC-J475DW_Printer.print_unwriteable_margin_bottom

0

print.printer_Brother_MFC-J475DW_Printer.print_unwriteable_margin_left

0

print.printer_Brother_MFC-J475DW_Printer.print_unwriteable_margin_right

0

print.printer_Brother_MFC-J475DW_Printer.print_unwriteable_margin_top

0

print.printer_Microsoft_Print_to_PDF.print_bgcolor

false

print.printer_Microsoft_Print_to_PDF.print_bgimages

false

print.printer_Microsoft_Print_to_PDF.print_duplex

-437918235

print.printer_Microsoft_Print_to_PDF.print_edge_bottom

0

print.printer_Microsoft_Print_to_PDF.print_edge_left

0

print.printer_Microsoft_Print_to_PDF.print_edge_right

0

print.printer_Microsoft_Print_to_PDF.print_edge_top

0

print.printer_Microsoft_Print_to_PDF.print_evenpages

true

print.printer_Microsoft_Print_to_PDF.print_footercenter

print.printer_Microsoft_Print_to_PDF.print_footerleft

&PT

print.printer_Microsoft_Print_to_PDF.print_footerright

&D

print.printer_Microsoft_Print_to_PDF.print_headercenter

print.printer_Microsoft_Print_to_PDF.print_headerleft

&T

print.printer_Microsoft_Print_to_PDF.print_headerright

&U

print.printer_Microsoft_Print_to_PDF.print_in_color

true

print.printer_Microsoft_Print_to_PDF.print_margin_bottom

0.5

print.printer_Microsoft_Print_to_PDF.print_margin_left

0.5

print.printer_Microsoft_Print_to_PDF.print_margin_right

0.5

print.printer_Microsoft_Print_to_PDF.print_margin_top

0.5

print.printer_Microsoft_Print_to_PDF.print_oddpages

true

print.printer_Microsoft_Print_to_PDF.print_orientation

0

print.printer_Microsoft_Print_to_PDF.print_page_delay

50

print.printer_Microsoft_Print_to_PDF.print_paper_data

1

print.printer_Microsoft_Print_to_PDF.print_paper_height

-1.00

print.printer_Microsoft_Print_to_PDF.print_paper_name

print.printer_Microsoft_Print_to_PDF.print_paper_size_unit

0

print.printer_Microsoft_Print_to_PDF.print_paper_width

-1.00

print.printer_Microsoft_Print_to_PDF.print_resolution

600

print.printer_Microsoft_Print_to_PDF.print_reversed

false

print.printer_Microsoft_Print_to_PDF.print_scaling

1.00

print.printer_Microsoft_Print_to_PDF.print_shrink_to_fit

true

print.printer_Microsoft_Print_to_PDF.print_to_file

false

print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_bottom

0

print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_left

0

print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_right

0

print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_top

0

privacy.clearOnShutdown.cookies

false

privacy.cpd.cookies

false

privacy.cpd.downloads

false

privacy.cpd.formdata

false

privacy.cpd.history

false

privacy.cpd.offlineApps

true

privacy.cpd.sessions

false

privacy.history.custom

true

privacy.sanitize.timeSpan

0

privacy.trackingprotection.introCount

20

privacy.userContext.enabled

false

security.dialog_enable_delay

0

security.disable_button.openCertManager

false

security.disable_button.openDeviceManager

false

security.sandbox.content.tempDirSuffix

{3e0d2d5d-9991-4734-85d5-63b01c9c4d78}

security.ssl.errorReporting.automatic

true

services.sync.declinedEngines

storage.vacuum.last.index

0

storage.vacuum.last.places.sqlite

1494788706

ui.osk.debug.keyboardDisplayReason

IKPOS: Touch screen not found.

ui.osk.enabled

false

user.js Preferences

Your profile folder contains a user.js file, which includes preferences that were not created by Nightly.

Important Locked Preferences
Name

Value

Places Database
Integrity

Verify Integrity

JavaScript
Incremental GC

true

Accessibility
Activated

false

Prevent Accessibility

0

Library Versions

Expected minimum version

Version in use

NSPR

4.15 Beta

4.15 Beta

NSS

3.31 Beta

3.31 Beta

NSSSMIME

3.31 Beta

3.31 Beta

NSSSSL

3.31 Beta

3.31 Beta

NSSUTIL

3.31 Beta

3.31 Beta

Experimental Features
Name

ID

Description

Active

End Date

Homepage

Branch

Sandbox
Content Process Sandbox Level

2



-----
Gary

**Comment by asamuzaK** [comment]
[Test Page](http://asamuzak.jp/test/addon_test "WebExtensions Tests")
(I created this markdown link with url2clipboard...)

Do you see
* "Absolute link" prompt when right click on first link -> Copy Link URL -> any format.
* "Relative link" prompt when right click on second link -> Copy Link URL -> any format.
* "Inner link (to textarea)" prompt when right click on third -> Copy Link URL -> any format.
* "WebExtensions Tests" prompt where else (Copy Link URL should not show).

**Comment by streetwolf** [comment]
Same issues on your test page.  Nothing goes to my clipboard so I can’t paste any links.  What is shown in the box after clicking on a link is just the address with no tags around it.

Examples:

Using the link ‘Absolute link” and “Relative Link”
Copy Link URL -> BBCode produces… Absolute link
Copy Link URL -> BBCode (URL) produces… http://asamuzak.jp/

Using the link “Inner link (to textarea)”
Copy Link URL -> BBCode produces… Inner link (to textarea)
Copy Link URL -> BBCode (URL) produces… http://asamuzak.jp/test/addon_test#textarea

Same sort of results for Copy Page URL.

-----
Gary

**Comment by asamuzaK** [comment]
Ah, press OK or Enter when prompt.
Paste somewhere and you will get the formatted text there.

Prompting is for customizing title.
Maybe it's confusing, I should think about another UI...

**Comment by asamuzaK** [comment]
Or, at least, make prompt message more obvious.

**Comment by streetwolf** [comment]
I am pressing OK/Enter.  What’s in the box doesn’t go to my clipboard as I can’t paste it.  The Paste option is gray.  Ctril-V doesn’t work either.  Also don’t forget the resulting text in your box is not formatted for any of the types (HTML, Markup, BBCode).  In other words it is useless on my system.

-----
Gary

**Comment by asamuzaK** [comment]
My result is:
"Absolute link" -> Copy Link URL -> BBCode:
`[url=http://asamuzak.jp/]Absolute link[/url]`
"Absolute link" -> Copy Link URL -> BBCode (URL):
`[url]http://asamuzak.jp/[/url]`

Do you see any errors in browser console (Ctrl + Shift + J) or web console (Ctrl + Shift + K)?

**Comment by streetwolf** [comment]
Let me try a new profile with only your add-on.  If still a problem I’ll cheek for error messages.  I’ll get back to you in a little while.

-----
Gary

**Comment by streetwolf** [comment]
Things appear to work with a new profile.  Since I can’t paste on my production profile I never realized, until I tried with a new profile, that the link box you produce doesn’t have any tags surrounding it.  Since I can’t paste I couldn’t tell if the tags were there.  The problem on my production profile might be that I can’t paste to see the tags.  Maybe you should put the tags in your box so the user can see it.

I think that you should rename some options.  BBCode for example produces the link and text name.  I think that should be BBCode (Text).  BBCode (URL) can remain the same.  This goes for the other options too.

I still have to figure out why I can’t paste as that might be the problem.

-----
Gary

**Comment by streetwolf** [comment]
After I set my test profile back to my production profile Paste is now working.  Very, very strange.

Let’s hope it stays working.  Here’s a suggestion.

BBcode as I said should become BBcode (Text).  The resulting link should only have the text as a link.  Currently you have the text above the link like this:

Preview: Re: [WARNING] Nightly might break some add-ons
https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAZEr8WLOzGlluRVMPfDep3SDx4MH3biks5r6HeYgaJpZM4NaclF

“Preview: Re: [WARNING] Nightly might break some add-ons” should be a link.  If so, no need for the link underneath it.

BBCode (URL) can remain the same.

You can probably make HTML also have a text only link as well as a URL only link.  Maybe the other too.




-----
Gary

**Comment by streetwolf** [comment]
I lost the ability to paste again.  If I try to paste in the search box for example the Paste is grayed out.  However in a reply box like on a forum it’s not grayed out but pasting doesn’t produce any links or text at all.  Weird.

Why going back to my production profile after using my test profile it worked and then when I exited Fx and started it up again I lost the ability to paste is strange.  My test profile shouldn’t have had an affect on my production file AFAICT.

-----
Gary

**Comment by asamuzaK** [comment]
You can do like this:
* Select `Preview: Re: [WARNING] Nightly might break some add-ons https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAZEr8WLOzGlluRVMPfDep3SDx4MH3biks5r6HeYgaJpZM4NaclF`
* Right click on `https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAZEr8WLOzGlluRVMPfDep3SDx4MH3biks5r6HeYgaJpZM4NaclF`

You need to edit prompt text though.

**Comment by streetwolf** [comment]
I deleted my prefs.js file and your add-on is working so far.  I do have a few issues though.

I went to the site and selected Copt Page URL BBCode (URL).  I got this when I pasted it into a forum comment box:

Preview: Re: When Aurora users will move to beta?
1364335 – stylo: Snapshot matching against states isn't right<https://bugzilla.mozilla.org/show_bug.cgi?id=1364335>

Where does the text come from?  Shouldn’t it be  Bug 1364335<https://bugzilla.mozilla.org/show_bug.cgi?id=1364335> - stylo: Snapshot matching against states isn't right


-----
Gary

**Comment by streetwolf** [comment]
Forget what I said below.  The text was just the title of the post.

-----
Gary

From: Gary Shapiro<mailto:garyshap@outlook.com>
Sent: Monday, May 15, 2017 1:25 PM
To: asamuzaK/url2clipboard<mailto:reply@reply.github.com>
Subject: RE: [asamuzaK/url2clipboard] Add ability to copy a link within the page (#6)

I deleted my prefs.js file and your add-on is working so far.  I do have a few issues though.

I went to the site and selected Copt Page URL BBCode (URL).  I got this when I pasted it into a forum comment box:

Preview: Re: When Aurora users will move to beta?
1364335 – stylo: Snapshot matching against states isn't right<https://bugzilla.mozilla.org/show_bug.cgi?id=1364335>

Where does the text come from?  Shouldn’t it be  Bug 1364335<https://bugzilla.mozilla.org/show_bug.cgi?id=1364335> - stylo: Snapshot matching against states isn't right


-----
Gary

**Comment by asamuzaK** [comment]
> BBcode as I said should become BBcode (Text)

Fixed in [commit 64df365831dd731a52b2194d595e2507c2f0321a](https://github.com/asamuzaK/url2clipboard/commit/64df365831dd731a52b2194d595e2507c2f0321a "Add (Text) to BBCode menu item · asamuzaK/url2clipboard@64df365")

I'll think more about what to do (or not to do) for other menu items.

> Or, at least, make prompt message more obvious.

Changed prompt message in [commit 254ee5c55accd9487decfd2a367c9aa9ca0d4498](https://github.com/asamuzaK/url2clipboard/commit/254ee5c55accd9487decfd2a367c9aa9ca0d4498 "Make prompt message clearer · asamuzaK/url2clipboard@254ee5c")

**Comment by asamuzaK** [comment]
Close the issue.
If something goes wrong, please feel free to file a new issue or reopen this one.

Thanks.

**Comment by asamuzaK** [comment]
Released v0.11.1 https://addons.mozilla.org/en-US/firefox/addon/withexeditor/
