### ISSUE TITLE
no show in context menu when only one format chosen

### ISSUE THREAD

**Issue by Sensor66** [asamuzaK/url2clipboard#60]
I need only the format "HTML --> text/html ".  This used to work well: just click on "Copy Page URL". 
Now (maybe after the last Firefox update), NO context menu item is shown for url2clipboard. 
Only when I select a **second** format, then it shows, with that submenu, e.g. HTML and LaTeX. 

Btw thanks for this great utility.

**Comment by asamuzaK** [comment]
Confirmed.
Thanks for the report.
Please wait for a while.

**Comment by Sensor66** [comment]
Wow, superfast action. It works now.
(After loading the xpi, it took some exiting/opening Firefox, at first no Options in the Add-on page, then a grayed out "Copy Page URL", but now the functionality is back.)

Thank you!

By the way, if I have feature requests, can I add them under Issuses ?

**Comment by asamuzaK** [comment]
> By the way, if I have feature requests, can I add them under Issuses ?

Welcome.
File a new feature request.
For example. [Feature Request: reStructuredText Format · Issue #43 · asamuzaK/url2clipboard](https://github.com/asamuzaK/url2clipboard/issues/43), [Need format for JIRA](https://github.com/asamuzaK/url2clipboard/issues/37) etc.

**Comment by asamuzaK** [comment]
Released v2.1.1
Should be downloaded soon.
