### ISSUE TITLE
Request: after link, no newline but a space without link

### ISSUE THREAD

**Issue by Sensor66** [asamuzaK/url2clipboard#61]
Feature request: 
I use text/html to paste links to e-mail (Thunderbird).  
With paste, what I get now is a link, followed by enter/newline, directly after the text plus link:
"[New Issue · asamuzaK/url2clipboard](url)
"

If I go to the line above and continue typing, what happens is that the link gets extended under my text. But I want to be able to type without the link:
"[New Issue · asamuzaK/url2clipboard](url) "

What I would like, is to get the text plus link, followed by a space without the link. And no enter/newline. 
In that scenario, I can type after the empty space, without the link being extended. 

Is that feasible?
Thanks.

**Comment by asamuzaK** [comment]
> With paste, what I get now is a link, followed by enter/newline, directly after the text plus link:

`br` element should not be added in this case.
I'll fix this part.

> If I go to the line above and continue typing, what happens is that the link gets extended under my text.

Bug of Thunderbird itself.
See [554264 - When typing text after inserting a link for selected text, link text style is not discontinued](https://bugzilla.mozilla.org/show_bug.cgi?id=554264)

> What I would like, is to get the text plus link, followed by a space without the link.

It will break compatibility with other.

**Comment by asamuzaK** [comment]
> What I would like, is to get the text plus link, followed by a space without the link.

How about workaround like the following?

* Copy URL as HTML
* Enter `space` in Thunderbird's mail composite window
* Go back one character with `<- (Home)` key
* Paste URL
* Go forward one character with `-> (End)` key

**Comment by asamuzaK** [comment]
I've uploaded another try build.

`a1` is simply adding space after HTML link
eg) `<a href="https://example.com">example.com</a> `

`a2` is adding `&nbsp;`(`&160;`) after HTML link
eg) `<a href="https://example.com">example.com</a>&160;`

Please tell me the results.
Thanks.

**Comment by Sensor66** [comment]
settings:
    
    
    So "Apply quick fix for Thunderbird" NOT selected.
    
    a1:  (testing with https://www.google.nl.)
    I pasted the link to the left margin, and next after that xxx.  Then
    I add yyy, or <space>yyy
    
    Googleyyy
    xxxGoogleyyy
    xxxGoogle yyy
    
    This works exactly as I would like !!  Or is this strange?? because
    "quick fix" has not been applied...
    
    a2:  
    Googleyyy
    xxxGoogleyyy
    xxxGoogle yyy
    
    Same results, good.
    
    a2:  with "Apply quick fix for Thunderbird"
    
    Google yyy
    xxxGoogle yyy
    xxxGoogle  yyy
    
    So same results, except for an extra <space> (is that
      &160; ?), which is visible. It
    seems possible to do without that, which is preferred.
     
    
    
    On 8-9-2018 18:09, asamuzaK (Kazz)
      wrote:
    
    
      
      I've uploaded another try build.
      a1 is simply adding space after HTML link
        eg) <a
          href="https://example.com">example.com</a>
      a2 is adding &nbsp;(&160;)
        after HTML link
        eg) <a
          href="https://example.com">example.com</a>&160;
      Please tell me the results.
        Thanks.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/asamuzaK/url2clipboard","title":"asamuzaK/url2clipboard","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/asamuzaK/url2clipboard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@asamuzaK in #61: I've uploaded another try build.\r\n\r\n`a1` is simply adding space after HTML link\r\neg) `\u003ca href=\"https://example.com\"\u003eexample.com\u003c/a\u003e `\r\n\r\n`a2` is adding `\u0026nbsp;`(`\u0026160;`) after HTML link\r\neg) `\u003ca href=\"https://example.com\"\u003eexample.com\u003c/a\u003e\u0026160;`\r\n\r\nPlease tell me the results.\r\nThanks.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/asamuzaK/url2clipboard/issues/61#issuecomment-419654273"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/asamuzaK/url2clipboard/issues/61#issuecomment-419654273",
"url": "https://github.com/asamuzaK/url2clipboard/issues/61#issuecomment-419654273",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [asamuzaK/url2clipboard] Request: after link, no newline but a space without link (#61)",
"sections": [
{
"text": "",
"activityTitle": "**asamuzaK (Kazz)**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@asamuzaK",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"asamuzaK/url2clipboard\",\n\"issueId\": 61,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"asamuzaK/url2clipboard\",\n\"issueId\": 61\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/asamuzaK/url2clipboard/issues/61#issuecomment-419654273"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 376726974\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by asamuzaK** [comment]
> So "Apply quick fix for Thunderbird" NOT selected.
> This works exactly as I would like !!  Or is this strange?? because "quick fix" has not been applied...

If it's working as expected, let's remove quick fix.

**Comment by asamuzaK** [comment]
Uploaded a new try build (v2.1.2a3)
If verified, let's close this issue.

**Comment by asamuzaK** [comment]
Installed Thunderbird 60.0 and verified that this issue is fixed in v2.1.2a3
I'll close this.
