### ISSUE TITLE
Create shortcut for copy?

### ISSUE THREAD

**Issue by ooker777** [asamuzaK/url2clipboard#65]
I would like to hit F2 for markdown, F3 for HTML copy. Is that possible?

**Comment by asamuzaK** [comment]
It is possible to implement shortcuts, but even if implemented, there will be a lot of limitations.

For example, in the Gecko browser shortcuts will not work with AMO or about:foo pages, and not with the Chrome web store in the Blink browser.
The context menu is grayed out on these pages, so the user will know that it can not be copied. However, with keyboard shortcuts, it is unable to know if it is copied correctly or not until you paste it.

Also, if you select a string as the content of the link format, copying the page will work, but copying the link (anchor) will not.

Those behavior will confuse the user.

So, at the moment, no plan to implement shortcuts.

See also: [Copy as default format by hotkeys directly? · Issue #15](https://github.com/asamuzaK/url2clipboard/issues/15)

**Comment by ooker777** [comment]
Actually after a while of using the browsers they will get that addons don't work in those pages, so they will have an expectation that it won't work. And we can also add a small notification in the corner to let them know whether the link is copied or not (like how Vimium works). This notification will clear all potential confusion.

**Comment by asamuzaK** [comment]
Accepted as a feature request.
However, I do not personally agree with the UI based on the user's experience.
So please understand that there is a possibility to reject it if it is determined that the UI is not good.

**Comment by asamuzaK** [comment]
Depends on #25

**Comment by asamuzaK** [comment]
Try build [url2clipboard/dest](https://github.com/asamuzaK/url2clipboard/tree/master/dest)

**Comment by ooker777** [comment]
I open the option page, but there is no section indicate the shortcut feature

**Comment by asamuzaK** [comment]
You can set shortcuts from add-on management page.

* Open "about:addons" (Ctrl + Shift + A)
* Click tools menu (gear icon on the upper right)
* Select "Manage Extension Shortcuts"

**Comment by ooker777** [comment]
Thank you. 

Is there a way to make the output of "Copy URL as HTML" really a hyperlink, not just HTML code?

**Comment by asamuzaK** [comment]
> Is there a way to make the output of "Copy URL as HTML" really a hyperlink, not just HTML code? (I'm talking about using shortcut, not by clicking the button)

Currently no.
Maybe in the future when navigator.clipboard.write is implemented both in Gecko and Blink.
See #25

**Comment by asamuzaK** [comment]
If you verified it's working as expected, please close this issue.

**Comment by ooker777** [comment]
Just wonder why the button click can give the hyperlink, while the shortcut can't

**Comment by asamuzaK** [comment]
Currently I use the same function and switching the copy method by giving mime-type as an argument.
That mime-type is loaded from the storage which user saved.
To be honest, shortcuts can be implemented even now, but I don't want to make current process more complicated just for shortcuts.

When clipboard.writeText and clipboard.write functions get implemented, the functions used will differ depending on the mime-type.
However, its implementation should require quite a lot of work, so I would like to implement shortcuts after that.

**Comment by asamuzaK** [comment]
Changed my mind.
Filed  #70
