### ISSUE TITLE
New Text & URL format

### ISSUE THREAD

**Issue by smaragdus** [asamuzaK/url2clipboard#74]
Hello,

I find your extension very useful. However I would like an alternative format for `Text & URL` command, the current format is Text & URL in one line, example:

- Wikipedia, the free encyclopedia https://en.wikipedia.org/wiki/Main_Page

The preferred format for me is Text & URL in separate lines, example:

- Wikipedia, the free encyclopedia
https://en.wikipedia.org/wiki/Main_Page

As a workaround I have to copy Text first then copy URL and paste them consecutively or copy Text & URL, paste and then edit, but this is not very handy. If there is new format which copies Text & URL in separate lines this will be extremely convenient for me since I collect a lot of articles and I will be able to copy Text & URL in my preferred format with a single click. Yes, there is an extensions which uses the format I prefer ([TabCopy](https://chrome.google.com/webstore/detail/tabcopy/micdllihgoppmejpecmkilggmaagfdmb)) but it is limited as it allows only 3 active formats in context menu and in tool bar button. If you decide to add the format I suggested above you may name it Text/URL.

Regards

**Comment by asamuzaK** [comment]
How about adding an option for that?
```
[ ] Text & URL
    [ ] Copy in separate lines
```

**Comment by smaragdus** [comment]
@asamuzaK 

Thanks for the immediate response.

For me it does not matter whether it would be implemented as an option in Options or as a new format if I can use it. You decide. But perhaps it would be more flexible if it is added as new format since the user may choose both formats to appear in the context menu.

**Comment by smaragdus** [comment]
@asamuzaK 

**Off-topic**

In options I have selected this toolbar button icon, screen:

![snipaste-2019-06-09_040959-1](https://user-images.githubusercontent.com/9025757/59153862-28acea80-8a6d-11e9-82c3-f623f46f24cb.png)

and it appears fine in the toolbar but in the context menu it appears another monochrome icon button, screen:

![snipaste-2019-06-09_041115-1](https://user-images.githubusercontent.com/9025757/59153872-5abe4c80-8a6d-11e9-9e5c-41833109c578.png)

Shouldn't the selected button icon in options appear both in the toolbar and in the context menu?

**Comment by asamuzaK** [comment]
About icon:
The root menu item icon cannot be changed dynamically.

**Comment by smaragdus** [comment]
@asamuzaK 

This was extremely fast, thank you.
