### ISSUE TITLE
Update locale

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/url2clipboard#76]
@gloomy-ghost 

Would you please update?
[diff](https://github.com/asamuzaK/url2clipboard/commit/8ff17e75a9c839ed3124c45b1f35c0a75fbc9591#diff-923564da56c4eee1688a23500af45265)

Thanks

**Comment by gloomy-ghost** [comment]
It's just a single line, so I'll just put it here. 
分行复制文本和链接
