### ISSUE TITLE
Add the format type to the copy dialog 

### ISSUE THREAD

**Issue by ooker777** [asamuzaK/url2clipboard#78]
When I use shortcuts to copy, I often forget what type of format the shortcut is. If possible, can you put that to the dialog box? 

![](https://i.imgur.com/ijlliqL.png)

**Comment by asamuzaK** [comment]
You mean like `Edit content text of the Markdown link`?

**Comment by ooker777** [comment]
Yes. Perhaps make the word bold too

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/url2clipboard/tree/master/dest)
