### ISSUE TITLE
url2clipboard doesn't work at https://addons.mozilla.org. 

### ISSUE THREAD

**Issue by streetwolf** [asamuzaK/url2clipboard#8]
Your add-on doesn't work anywhere on https://addons.mozilla.org.  I know Mozilla made this a 'special' sort of site.   Probably some kind of security thing.  Other add-ons also don't work on these pages.  Don't really know if you can do anything about it.

**Comment by asamuzaK** [comment]
[1310082 - WebExtension content script not working on mozilla.org sites](https://bugzilla.mozilla.org/show_bug.cgi?id=1310082 "1310082 - WebExtension content script not working on mozilla.org sites")

**Comment by asamuzaK** [comment]
BTW you can use copy2clipboard if you access AMO with Blink based browsers.
But Blink + copy2clipboard don't work on Chrome webstore though.
