### ISSUE TITLE
Copying from context menu fails

### ISSUE THREAD

**Issue by smaragdus** [asamuzaK/url2clipboard#80]
Copying from tool bar button works fine but copying from context menu (`Copy Page URL`) fails, this happens with **Copy URL To Clipboard** version **3.1.0**. Yes, I have refreshed the web pages after the update. Can you confirm the problem? Or perhaps it appears only in my browser?

A side note- `Copy text and URL in separate lines` option for  `Text & URL` works fine when executed from tool bar button, thanks for this new option.

**Comment by asamuzaK** [comment]
Which browser?

**Comment by smaragdus** [comment]
@asamuzaK 

[CentBrowser](https://www.centbrowser.com/) [version](https://www.centbrowser.com/history.html) **4.0.9.112** (portable, 32-bit).

**Comment by asamuzaK** [comment]
Ah, confirmed on Vivaldi too.

**Comment by smaragdus** [comment]
I have Vivaldi too but I rarely use it.

**Comment by smaragdus** [comment]
I simply forgot that **Copy URL To Clipboard** is available for both Chromium-based and Firefox-based browsers. I will check the extension with some other browsers too,

**Comment by smaragdus** [comment]
On Firefox copying from context menu works just fine.

**Comment by smaragdus** [comment]
I also tested **Copy URL To Clipboard** with [Iridium Browser](https://iridiumbrowser.de/) (version **2019.4.73.0**) and copying from context menu failed too.

**Comment by asamuzaK** [comment]
Released v3.1.1
Should be downloadable soon.

Thanks for your contribution.

**Comment by smaragdus** [comment]
@asamuzaK 

Thank you very much for the quick fix. On [Chrome Web Store](https://chrome.google.com/webstore/detail/copy-url-to-clipboard/miancenhdlkbmjmhlginhaaepbdnlllc) it is still version **3.1.0**. When version **3.1.1** is available I will test it.

If it happens that I come across problems in the future I will notify you.

Have a great day.

**Comment by smaragdus** [comment]
Copying from context menu still does not work with browsers such as Iridium (version mentioned above) which are based on older versions of Chromium.

**Comment by asamuzaK** [comment]
Installed Iridium and confirmed the issue.

But weird...
It is in try-catch statement, so error should be thrown, not undefined.

```
clipboard.js:91
Uncaught (in promise) TypeError: Cannot read property 'name' of undefined at Clip.copy (clipboard.js:91)
```

**Comment by asamuzaK** [comment]
Released v3.1.2

**Comment by smaragdus** [comment]
@asamuzaK 

Thanks for the quick response and fix,

I should have told you that you don't need to install it- you can download an archive ([downloads](https://downloads.iridiumbrowser.de/windows/)) and use it in portable mode by starting it with the following parameter:

`iridium.exe --user-data-dir=IridiumUserData`

so data is saved not in `AppData` but in `IridiumUserData` sub-folder of program folder. For me portable mode is better for testing.

[Chrome Web Store](https://chrome.google.com/webstore/detail/copy-url-to-clipboard/miancenhdlkbmjmhlginhaaepbdnlllc) is still at version **3.1.1**, when version **3.1.2** is available I will have a look.

Thank you for fixing the problem!

**Comment by smaragdus** [comment]
@asamuzaK 

I have just updated to version **3.1.2**, the problem is really fixed, thank you!
