### ISSUE TITLE
Selecting icon in settings doesn't cause change

### ISSUE THREAD

**Issue by bladewolf55** [asamuzaK/url2clipboard#93]
In Chrome and Brave, selecting a different icon in the Settings page doesn't change the icon. It's always a dark border,which is hard to see on a dark theme.

All other functions work perfectly...though I would love a keyboard shortcut to copy all open tabs in the various formats, not just the current tab.

**Comment by asamuzaK** [comment]
Works:

* Google Chrome Canary
  Version 83.0.4088.0 (Official Build) canary (64-bit)
* Vivaldi 2.12.1854.5
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.66 Safari/537.36

Wont work:
* Brave
  Version 1.5.112 Chromium: 80.0.3987.132 (Official Build) (64-bit)

Seems like Blink version specific issue?

**Comment by bladewolf55** [comment]
OK. Thanks for checking into it. I literally just downloaded and installed
the actual official build of Chrome Browser, which is:

Google Chrome is up to date
> Version 80.0.3987.149 (Official Build) (64-bit)


The same icon problem occurs, as expected.

Chrome Canary is cutting edge and not stable, so that's not a good test for
standard users.


--
Charles L Flatt
513-535-0764 (m)
"Capitalism at its most ruthless rewards psychopathic behavior." --Robert
Hare, inventor of the psychopath checklist.

**Comment by asamuzaK** [comment]
Ref [1056106 - Extension - chrome.browserAction.setIcon doesn't work on chrome version 80 - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1056106)

It's marked as `WontFix`.

**Comment by bladewolf55** [comment]
Understood. I wait for the fix in the future Chrome version.

**Comment by asamuzaK** [comment]
I will close this.
