### ISSUE TITLE
Copy URLs of other tabs

### ISSUE THREAD

**Issue by vavavr00m** [asamuzaK/url2clipboard#94]
As the title says, please add copy URLs of all tabs except the active tab with a shortcut key, if possible?

**Comment by asamuzaK** [comment]
It's possible to add a "Copy URLs of other tabs" menu to a toolbar button.

But, for the keyboard shortcut, no.
Both Firefox and Chrome does not prepare a UI for a shortcut with a choice like "Do foo as [bar, baz]".

**Comment by vavavr00m** [comment]
Sure that would be cool if it's a 1-click button. Thank you if you're going to add it.

**Comment by asamuzaK** [comment]
Fixed.
Please wait for the next release (maybe next month).

**Comment by vavavr00m** [comment]
Okay it works on FF, thank you. Is there any way to set one particular action (copy other tabs URLs) as the button action instead of a menu of items?

**Comment by asamuzaK** [comment]
WebExtensions doesn't have an API to do that.

**Comment by vavavr00m** [comment]
How is [Reload All Tabs](https://mybrowseraddon.com/reload-all-tabs.html) able to assign reload to the menu button?

**Comment by asamuzaK** [comment]
Extension can assign any function to the toolbar button, but basically only one.
`browser.browserAction.onClick.addListener(callback)`

This extension is assigning to show a popup on click, maybe that extension is calling browser.tabs.reload() or something (I did not take a look at it).
