### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by r1ma952** [asamuzaK/url2clipboard#98]
I got email that this is for Firefox, the latest version of the addon url2clipboard.
The other one is for Edge Chromium? 
![image](https://user-images.githubusercontent.com/59985569/85606398-5ceb4d00-b668-11ea-8e48-ba2f8d729213.png)

**Comment by r1ma952** [comment]
By the way, for Firefox now its fixed. There is no need to go to the open Tab and from there go to the right-click menu.

**Comment by asamuzaK** [comment]
No, that is a folder for source codes.
No try builds for Blink because Google does not provide good and easy way for testing.
Release version will be out in a week or so.

**Comment by r1ma952** [comment]
Thank you, the first one which was for Firefox "url-6.0.0a1-fx.xpi", was the latest version of the addon, or the beta? 
So for the Chromium Edge, it will be out in a week or so? I have to check the https://chrome.google.com/webstore/detail/copy-url-to-clipboard/miancenhdlkbmjmhlginhaaepbdnlllc
right? 
Thank you again.

**Comment by asamuzaK** [comment]
> Thank you, the first one which was for Firefox "url-6.0.0a1-fx.xpi", was the latest version of the addon, or the beta?

It's a beta.

> So for the Chromium Edge, it will be out in a week or so? I have to check the https://chrome.google.com/webstore/detail/copy-url-to-clipboard/miancenhdlkbmjmhlginhaaepbdnlllc
> right?

Right, but you don't have to check it.
Both Firefox extension and Chrome (and others) extension will update automatically.

**Comment by asamuzaK** [comment]
By the way, even in the current release version (v5.0.2), if you reload the YouTube page and then copied, the correct link will be applied.

**Comment by r1ma952** [comment]
Yes, reloading the page worked. But there is a fix coming, right?

**Comment by asamuzaK** [comment]
New version released a couple days ago.
Please check if it's working?

Thanks

**Comment by r1ma952** [comment]
Hi, I testes with few videos and it works correctly. Thank you.
