### ISSUE TITLE
take url to specific site

### ISSUE THREAD

**Issue by gnfb1234** [asamuzaK/url2clipboard#99]
Hope i am in the right place to ask if possible to add a "function" ability to 1 . copy the url 2. then direct to specific site ?

**Comment by asamuzaK** [comment]
Technically, it's possible.
I assume you want to do two things at once, but I don't see much reason to implement this feature.

* In the first place, it's out of the scope of what this extension provides.
* Even if there is an options like "When copying a link, go to the link after copying it", you still need sub-options like "Open in Current Tab", "Open in New Tab", "Open in New Window", and "Open in New Private Window".
* However, not everyone wants the same action every time.
  Depending on the context of the link, you may want to open a link in the same tab, or in other case in a new tab.
* There could be an option like "Choose how to open links each time", but that doesn't satisfy your need to do two things at once.

**Comment by tex** [comment]
Look at my request #100. With CopyQ you could have automatic action using whatever tool you have available on your platform to send the url wherever you want.

**Comment by asamuzaK** [comment]
@gnfb1234 
Please explain your use case a bit more.

**Comment by asamuzaK** [comment]
No info, I'm closing this now.
Feel free to reopen when you have some additional info.
